# Generated by Django 5.0.6 on 2024-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slig',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
