# Generated by Django 5.0.6 on 2024-10-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_slig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slig',
            new_name='slug',
        ),
    ]
